### ISSUE TITLE
Javascript error when using seach 

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1048]
Hi everyone. I am using converjs 3.3.2 with ejabberd 18.1 under ubuntu 16.04.
I have enabled search as you can see in the following code.

```
xhr_user_search: true,
xhr_user_search_url: site_url + 'chat_user_search',
```

When I use firefox search works perfectly. But under other browser (opera version 46.0 and chrome version 62.0.) search does not work and I have the following javascript error in the console.

```
converse.js:48000 Uncaught TypeError: u.appendChild is not a function
    at converse.js:48000
    at arrayEach (converse.js:4462)
    at Function.forEach (converse.js:13284)
    at XMLHttpRequest.xhr.onload (converse.js:47993)
```
I have the same error when I use the lastest converjs release (3.3.4). 

Could someone help me ?

**Comment by jcbrand** [comment]
This is a bug in 3.3.4.

I've noticed this as well. I'm currently working on the 4.0.0 release and have updated and fixed `xhr_user_search_url` in master for the upcoming 4.0.0 release.

**Comment by rheman** [comment]
Thanks a lot...

**Comment by rheman** [comment]
Please How can I solve this issue in 3.3.4. 
Best regard
