### ISSUE TITLE
Conversejs error after migration from 3.3.4 to 4.2.0

### ISSUE THREAD

**Issue by rheman** [conversejs/converse.js#1558]
Hi I used to use conversejs 3.3.4 on my website with requirejs and it worked perfectly.
Today I have decided to migrate from 3.3.4 to 4.2.0  and I get a lot of  errors.
- xmpp sever: ejabberd 19
- Linux server: ubunti 18.04
- converjs 4.2.0

I get the following errors:

```
TypeError: this.get is not a function                   converse.js:64979:17
ERROR: request id 2.1 error 403 happened      converse.js:63317:5
too much recursion                                             converse.js:65283:11
too much recursion                                             converse.js:1737:5
too much recursion                                             converse.js:1378:5
```

My conversejs setting looks as followed.

   ```
var view_mode = elgg.data.pessek_chat.view_mode;
    var user_jid = elgg.data.pessek_chat.user_jid;    
    var bosh_service_url = elgg.data.pessek_chat.bosh_service_url; 
    var websocket_url_non_secure = elgg.data.pessek_chat.websocket_url_non_secure;
    var websocket_url_secure = elgg.data.pessek_chat.websocket_url_secure;
    var credentials_url = elgg.data.pessek_chat.credentials_url;     
    var prebind_url = elgg.data.pessek_chat.prebind_url;   
    var userxmppdomain = elgg.data.pessek_chat.userxmppdomain;
    var sounds_path = elgg.data.pessek_chat.sounds_path;
    var emojione_image_path = elgg.data.pessek_chat.emojione_image_path;
    var site_url = elgg.data.pessek_chat.site_url;
    var locales_url = elgg.data.pessek_chat.locales_url;
    var user_jid_pass = elgg.data.pessek_chat.user_jid_pass; 
    var language_code = elgg.get_language(); 
   
 converse.initialize({
	authentication: 'prebind',        
	prebind_url: prebind_url,
        bosh_service_url: bosh_service_url,
        view_mode: view_mode,
            keepalive: true, 
            jid: user_jid,
            allow_logout: false,
            allow_muc: false,
            notification_icon: emojione_image_path + 'pessek.jpg',
            muc_instant_rooms: false,
            allow_muc_invitations: false,
            allow_non_roster_messaging: true,
            allow_otr: true,
            cache_otr_key: true,
            forward_messages: true,
            roster_groups: false,
            allow_contact_requests: false,
            allow_chat_pending_contacts: false,
            allow_contact_removal: false,
            auto_reconnect: true,
            auto_login: true,
            animate: true,
            message_archiving: 'always',
            i18n: language_code,
            locales_url: locales_url,
            csi_waiting_time: 60,
            auto_away: 300,
            ping_interval: 180,
            archived_messages_page_size: 70,
            message_carbons: true,
            default_domain : userxmppdomain,
            allow_registration: false,
            debug: true,
            sounds_path: sounds_path,
            play_sounds: true,
            xhr_user_search_url: site_url + 'chat_user_search',
            show_controlbox_by_default: true,
            strict_plugin_dependencies: false,
            synchronize_availability: true,
            visible_toolbar_buttons: {
                call: true,
                emoji: true,
		spoiler: true,
                toggle_occupants: true
            },
    });
```

**Comment by jcbrand** [comment]
Did you manage to get this working?

**Comment by rheman** [comment]
No I still get the same error

**Comment by jcbrand** [comment]
There isn't enough info in your bug report to know what's going on. Do you have any plugins or customizations to Converse?

**Comment by rheman** [comment]
Hi,
I do not have any plugins and I do not have any customizations.
My  firefox console display the following errors:

`TypeError: this.get is not a function[Learn More]                  converse.js:64979:17`

Bellow are two screenshots of my console.

![Screenshot from 2019-05-09 23-08-53](https://user-images.githubusercontent.com/4598772/57490197-5f49e680-72b0-11e9-9bab-a826a4c095b4.png)

![Screenshot from 2019-05-09 23-13-59](https://user-images.githubusercontent.com/4598772/57490204-6a047b80-72b0-11e9-93fa-8a6eb78c7cf8.png)

Regards

**Comment by jcbrand** [comment]
Thanks for the additional info, should be fixed now in master.

For now, as a workaround, if you set `forward_messages` to `false`, then the problem should go away.
That option is in any case no longer necessary in most cases because the servers support message carbons.

**Comment by rheman** [comment]
Thanks a lot for your answer.
I set `forward_messages` to `false` in my settings. But one error is remaining, as you could see on the screenshot.

![Screenshot from 2019-05-13 18-33-12](https://user-images.githubusercontent.com/4598772/57641847-ef887400-75ad-11e9-8eea-57537d5b3063.png)


Regards,

**Comment by jcbrand** [comment]
I think the Firefox error can be ignored, it's a low-level Strophe error from which it generally recovers.

I'm not sure what the other error is about...

**Comment by jcbrand** [comment]
I'm closing this ticket as a `wontfix`. We don't have the resources to deal with this.
